name: 'RUN WEBSITE TESTS:'
on:
  pull_request:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      - DJANGO_RUN_MODE: DEVELOPMENT
      - DJANGO_SECRET_KEY: dev_secret_key

    steps:
      # name: Clone Repository into our runner-environment
      - uses : actions/checkout@v4

      # name: setup python in this container
      - uses: actions/setup-python@v5
        with:
          python-version : 3.11.3

      # name: Upgrade PIP
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: python manage.py test



